version: '3.8'

services:
  api_pfr2:
    # build:
    #   context: ./API_PFR2
    #   dockerfile: Dockerfile
    image: ghcr.io/naelle47/api_pfr2:master
    # image : ghcr.io/naelle47/api_pfr2:latest
    ports:
      - "32768:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development